from fpdf import FPDF
import os
from datetime import datetime
import uuid

# Ensure reports folder exists
REPORT_FOLDER = "static/reports"
os.makedirs(REPORT_FOLDER, exist_ok=True)


def generate_pdf(prediction, confidence, fertilizer, pesticide, organic):
    """
    Generate PDF report for plant disease prediction
    Returns the path of generated PDF
    """

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # -------- Title --------
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "AgriCare - Plant Disease Report", ln=True, align="C")
    pdf.ln(5)

    # -------- Date --------
    pdf.set_font("Arial", size=11)
    pdf.cell(0, 8, f"Generated On: {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}", ln=True)
    pdf.ln(5)

    # -------- Prediction Details --------
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Prediction Summary", ln=True)
    pdf.ln(3)

    pdf.set_font("Arial", size=11)
    pdf.cell(0, 8, f"Disease Detected : {prediction}", ln=True)
    pdf.cell(0, 8, f"Confidence Level : {confidence}%", ln=True)
    pdf.ln(5)

    # -------- Fertilizer --------
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Fertilizer Recommendation", ln=True)
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 7, fertilizer)
    pdf.ln(3)

    # -------- Pesticide --------
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Pesticide Recommendation", ln=True)
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 7, pesticide)
    pdf.ln(3)

    # -------- Organic Treatment --------
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Organic Treatment Recommendation", ln=True)
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 7, organic)
    pdf.ln(8)

    # -------- Footer --------
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 8, "Generated by AgriCare | Smart Farming Assistant", ln=True, align="C")

    # -------- Save File --------
    filename = f"AgriCare_Report_{uuid.uuid4().hex}.pdf"
    filepath = os.path.join(REPORT_FOLDER, filename)
    pdf.output(filepath)

    return filepath
